<?php

namespace App\Actions;

use Genocide\Radiocrud\Services\ActionService\ActionService;
use App\Models\Classes;
use App\Http\Resources\ClassResource;

class ClassAction extends ActionService
{
    public function __construct()
    {
        $this
            ->setModel(Classes::class)
            ->setResource(ClassResource::class)
            ->setValidationRules([
                'store' => [
                    'name' => ['required', 'string', 'max:150']
                ]
            ])
            ->setCasts([
                'image' => ['file', 'nullable']
            ]);
        parent::__construct();
    }

    public function delete(callable $deleting = null): mixed
    {
        foreach ($this->eloquent->get() AS $entity)
        {
            unset($entity->image);
        }
        return parent::delete($deleting); // TODO: Change the autogenerated stub
    }

    public function getFirstByEloquent($eloquent = null): object
    {
        return parent::getFirstByEloquent($eloquent); // TODO: Change the autogenerated stub
    }
}
